### ISSUE TITLE
셋팅관련 문의 드립니다. 

### ISSUE THREAD

**Issue by green1657** [JonghyeokPark/SWE3003#10]
Cannot find a valid baseurl for repo: ol7_MySQL55

페이지 5의 과정을 이행했음에도 위와 같은 문구가 git  설치 뜹니다.

**Comment by JonghyeokPark** [comment]
sudo vim /etc/yum.repos.d/public-yum-ol7.repo 해당 파일을 수정하신 것 맞나요?
(1이 아니라, 영어 소문자 L 입니다.)

**Comment by green1657** [comment]
![image](https://user-images.githubusercontent.com/38343857/38722513-1b720466-3f39-11e8-9bdd-0b42272d7ffc.png)
![image](https://user-images.githubusercontent.com/38343857/38722539-2b90d62e-3f39-11e8-8479-34fdf15e135c.png)
네. 이렇게 수정한 후 진행하였습니다.

**Comment by JonghyeokPark** [comment]
확실하지는 않지만, indent (들여쓰기) 문제일수도 있습니다.
baseurl, gpgkey  이 항목을 들여쓰지 않고 수정해주세요.
