### ISSUE TITLE
과제 내용 질문 드립니다

### ISSUE THREAD

**Issue by ghost** [JonghyeokPark/SWE3003#11]
저희가 짠 sql구문이 오라클 sql에서 정상적으로 테이블을 띄워주며 동작하는데
파이썬 코드에 sql구문 삽입시 정상적으로 동작하지 않습니다
상단에 Result not found라고 뜨고 
테이블엔 필드 이름만 뜨고 value가 뜨지 않습니다
왜 그런건지 궁금합니다

**Comment by JonghyeokPark** [comment]
어느 상황에서 발생한것인지 확인이 힘듭니다. 혹시 sql과 해당 화면 스크린샷을 볼 수 있을까요?

**Comment by ghost** [comment]
![kakaotalk_20180416_204148638](https://user-images.githubusercontent.com/37765512/38807195-d414045e-41b6-11e8-9d52-8a182c692e8f.jpg)
![kakaotalk_20180416_204148999](https://user-images.githubusercontent.com/37765512/38807196-d43f111c-41b6-11e8-84b2-b613be363782.jpg)

이렇게 뜹니다

**Comment by JonghyeokPark** [comment]
executeSQL_V1, executeSQL_V2 함수를 알맞게 사용하셨나요?
V1 : 여러 select 결과를 테이블 형식으로 출력함.
V2 : 평균 값, 총 갯수 등의 단일 변수 값을 출력함.

**Comment by ghost** [comment]
sql 상에 테이블로 결과가 뜨는 건 v1 함수를 썼습니다
fetchall 이 안되는 거 같은데 혹시 제 짐작이 맞는지 궁금합니다
아니면 혹시 sql에서 scott/tiger 계정으로 테이블을 생성하여 작업했는데
scott/tiger 계정으로 연결이 안되는건가요?

**Comment by JonghyeokPark** [comment]
views.py에서 scott, tiger로 접속하는 부분을 고치지 않으셨다면, 현재상태에서 접속에 대한 에러는 없는 것 같습니다.
질문해주신 스크린샷에 있는 비슷한 쿼리문을 돌려봤는데 잘 출력이 되었습니다.
쿼리문 입력한 변수를 다시한번 확인해주세요. 
혹시 쿼리문안에 문자열 때문에 따옴표를 사용하시나요?

**Comment by ghost** [comment]
쿼리안에 따옴표는 사용하지 않았습니다
설정상에 문제가 있었는지 다른 방법을 찾아서 해결하였습니다
조언 감사합니다

**Comment by JonghyeokPark** [comment]
혹시 해당 문제 해결 방법 공유해주실 수 있으신가요?

**Comment by green1657** [comment]
그냥 scott계정이 orcl을 디폴트로 가지길래 tnsname.ora 파일 좀 수정했습니다. listener 만들어주고요
