### ISSUE TITLE
과제 내용 질문드립니다.

### ISSUE THREAD

**Issue by gwiseki** [JonghyeokPark/SWE3003#12]
사용자에게 정보를 입력 받아 실제 예약을 할 수 있는 예약 시스템을 구현해야 되나요?
그러면 views.py 파일에 Modify here 부분 말고 위에 부분도 수정해도 되나요?

**Comment by JonghyeokPark** [comment]
views.py에서 논리적으로 오류가 없는 수정은 자유롭게 하셔도 됩니다. 
기차예약 시스템에서 필요한 내용을 기반으로 데이터베이스를 설계하는 것입니다. 자유롭게 설계하시고, 보고서에 설명을 작성하시면 됩니다.
