### ISSUE TITLE
셋팅관련 문의드립니다.

### ISSUE THREAD

**Issue by kim-sang-yub** [JonghyeokPark/SWE3003#13]
파이썬 설치과정에서 오류가 발생합니다.

scl enable rh-python35 -- bash 명령어 입력에서서
![1](https://user-images.githubusercontent.com/38370439/38765373-13ea64be-3ffb-11e8-98c8-94228617b2ab.png)

다음과 같이 오류가 발생합니다...

그 이전의 설치과정에서는 모두 순차적으로 진행되었습니다만

해당 명령어에서 갑자기 더 이상 진행이 되지 않습니다...

**Comment by JonghyeokPark** [comment]
sudo yum install gcc scl-utils rh-python35 
해당 명령어로 파이썬이 잘 설치를 진행하셨나요?

**Comment by kim-sang-yub** [comment]
![1-1](https://user-images.githubusercontent.com/38370439/38781926-9118c214-4127-11e8-8a51-7c63a1fb4cf3.png)
![1-2](https://user-images.githubusercontent.com/38370439/38781928-92563e9a-4127-11e8-90f5-cc909ae4d9c4.png)
![1-3](https://user-images.githubusercontent.com/38370439/38781930-941fe41a-4127-11e8-82e1-7628ebb3b19f.png)
![1-4](https://user-images.githubusercontent.com/38370439/38781931-95b26154-4127-11e8-906c-df2657a74244.png)

위의 화면들 처럼 원활하게 진행되었는데, 4번째 화면처럼 열 수 없다고 나옵니다.

물론 이후 파이썬 버전을 확인하면 당연히 2.7.5버전이 나옵니다.
