### ISSUE TITLE
서버 세팅 관련 질문

### ISSUE THREAD

**Issue by hoseung2** [JonghyeokPark/SWE3003#14]
![image](https://user-images.githubusercontent.com/26895895/38766279-7efc31e2-400a-11e8-94ca-09e44d450097.png)

scott대신 새로 유저를 만들어서 테이블을 구성했는데 dsn이 달라서 그런지 경로를 찾을 수 없다고 뜹니다. 어떻게 해결할수있을까요??

**Comment by JonghyeokPark** [comment]
새로 만든 계정인 korail에 권한이 부여되어있지 않아서 생긴 문제일 수 있습니다. 해당 계정에 권한을 부여해주세요.
