### ISSUE TITLE
세팅관련 질문입니다.

### ISSUE THREAD

**Issue by kingh2160** [JonghyeokPark/SWE3003#15]
![default](https://user-images.githubusercontent.com/38389986/38774183-7e3c222e-409d-11e8-84a0-2ed57bd0b205.png)

TeamProject PDF파일에 있는 14, 15, 16 page를 그대로 작성하여 views.py를 웹페이지에서 확인하려고 하는데 위와 같이 에러가 뜹니다.

cx_Oracle 패키지도 잘 설치하였고, 이후
python -m pip install cx_Oracle --upgrade 등의 명령어로 계속 진행해봤지만, 해결되지 않았습니다.

**Comment by JonghyeokPark** [comment]
다음 사항을 고려해보세요.
1) myvenv 를 활성화시키기 전에, scl enable rh-python35 -- bash 해당명령어 입력하셨나요?
2) python35 버전에서 수행하는 것인지? (python --version 입력하면 3.5.x 버전이 나와야 합니다.)

**Comment by kingh2160** [comment]
![default](https://user-images.githubusercontent.com/38389986/38785287-06db7a9c-4159-11e8-806a-bf1734ac8389.png)
네, 그대로 진행하였습니다.

**Comment by JonghyeokPark** [comment]
cx_Oracle 설치가 재대로 되었는지 확인부탁드립니다.
myvenv 활성화 후에 아래 스크린샷처럼 명령어 입력하여, cx_Oracle 버전을 확인해주세요.
나오지 않는다면, 설치가 제대로 안된 것입니다.
![image](https://user-images.githubusercontent.com/7540698/38786668-4d98f724-4164-11e8-935a-c12f906e78b7.png)

**Comment by kingh2160** [comment]
![default](https://user-images.githubusercontent.com/38389986/38788400-697030b6-416e-11e8-9143-c62485e1f2e9.png)
해당 cx_Oracle 문제는 views.py파일에 import 문제였던 것 같습니다. 지금은 위 사진처럼 해결되었습니다.
![default](https://user-images.githubusercontent.com/38389986/38788481-dc7a5a32-416e-11e8-9aa5-d4d19489e652.png)
위 사진과 같이 명령어를 친 뒤, localhost:8000를 치면 아래와 같이 
![default](https://user-images.githubusercontent.com/38389986/38788506-10e7570c-416f-11e8-9f8e-cd462cb6fd64.png)
에러가 발생합니다. 이 부분은 어떻게 해결해야 하나요?

**Comment by JonghyeokPark** [comment]
지금 확인해보니, 실행명령어가 잘못되었네요.
manage.py 파일이 있는 디렉토리상에서 아래와 같이 명령어를 입력해주세요.

python manage.py runserver 0.0.0.0:8000

**Comment by kingh2160** [comment]
감사합니다.
혹시, 엑셀파일로 만들어 놓은 튜플들을 바로 table에 insert할 수 있는 방법이 있을까요??
