### ISSUE TITLE
[과제 내용] 과제 내용 관련 질문이 있습니다.

### ISSUE THREAD

**Issue by eunjeung** [JonghyeokPark/SWE3003#16]
5.Handling duplicates in your table
•There are duplicate values in your table do not allow duplicates.

이 항목에서는 select 문에서 중복이 존재하지 않도록 쿼리문을 작성해야 하는건가요
아니면 애초에 table을 만들 때부터 중복이 존재하지 않도록 설정을 해야하는 건가요?

**Comment by JonghyeokPark** [comment]
테이블에 "중복"된 dummy data를 넣으시고 출력할 때 중복이 존재하지 않도록 하는 것입니다.
아래 참고해주세요. 
https://github.com/JonghyeokPark/SWE3003/issues/6

**Comment by eunjeung** [comment]
그러면 조회를 했을 때 출력된 데이터가 중복이 존재하지 않도록만 하면 되는 것인가요?
PK 조건 상 완벽하게 중복되는 데이터는 넣을 수 없을 것 같은데요

**Comment by JonghyeokPark** [comment]
PK로 지정된 column말고, 다른 column에서 중복이 발생하도록 dummy data를 넣어주시고, 
해당 column을 출력할 때 중복이 발생하지 않도록 하는 것은 어떨까요?

**Comment by eunjeung** [comment]
아, 이제 완벽히 이해되었습니다. 감사합니다.
