### ISSUE TITLE
테이블 생성 질문드립니다.

### ISSUE THREAD

**Issue by wlaud1001** [JonghyeokPark/SWE3003#17]
![default](https://user-images.githubusercontent.com/28920463/38787910-c4f2d02c-416b-11e8-8305-c300a243077c.png)
![default](https://user-images.githubusercontent.com/28920463/38787911-c518d7b8-416b-11e8-838b-4ab812abd1dc.png)

views.py안에서 테이블생성을 어떻게 해야하는 지 모르겠어서 질문드립니다.

**Comment by JonghyeokPark** [comment]
해당 테이블 생성 sql 문에는 문제가 없습니다.
다만, Django 프레임워크상에서 cx_Oracle로 테이블을 생성하려면 오라클 버전 (12c)에 맞는 cx_Oracle설치를 해야 합니다. 
따라서, 테이블 생성할 때에는 views.py로 하지 않고, sqlplus상에서 진행해주세요.
과제 제출할 때 생성한 테이블들을 덤프해서 제출해주시면 됩니다.

**Comment by wlaud1001** [comment]
죄송하지만 sqlplus상에서 진행한다는게 어떤 건지 알 수 있을까요?
sqlplus로 어떻게 진입하는건가요??

**Comment by JonghyeokPark** [comment]
기존의 스크립트 예제 실행하시던 것처럼 터미널에서 sqlplus 실행시켜서 하시면 됩니다.

터미널 열고 
sqlplus scott/tiger  (로그인)
테이블 및 데이터 넣기
