### ISSUE TITLE
과제 5번 질문드립니다.

### ISSUE THREAD

**Issue by green1657** [JonghyeokPark/SWE3003#18]
과제 5번이 테이블 입력시 프라이머리 키 값 등으로 무결성을 체크 하는것을 구현하라는 것인지
테이블상에서는 중복이 허용되나 출력 할 때 중복을 제거 하라는 것인지 궁금합니다.

**Comment by JonghyeokPark** [comment]
아래 내용 참고해주세요.
https://github.com/JonghyeokPark/SWE3003/issues/6
