### ISSUE TITLE
고제 제출 질문드립니다.

### ISSUE THREAD

**Issue by wlaud1001** [JonghyeokPark/SWE3003#19]
자신의 database dump file을 제출하라고 하셨는데 어떻게 하는 건지를 모르겠어서 질문드립니다.

**Comment by JonghyeokPark** [comment]
I-Campus에 업로드된 과제 안내서  20 페이지를 보시면 "How to Dump?" 가 있습니다.
과제를 위해 생성한 테이블들을 덤프해주시고 같이 업로드해주시면 됩니다.

**Comment by wlaud1001** [comment]
파일 dump까지는 교안을 보고 완료했습니다. 그런데 이제 그 덤프된 파일을 어떻게 가져올 수 있는지 알려주실 수 있으신가요? 가상머신 안에서 제출을 해야하는 건가요?

**Comment by JonghyeokPark** [comment]
1) 가상 머신안에서 Filefox로 메일을 보내는 방법이 있습니다. 
(다음 메일을 사용하면 대용량 메일을 사용할 수 있습니다.)

2) 혹시, USB를 PC에 꽂았을 때, VM에서도 인식이 된다면 해당 방법 사용하시면 됩니다.
