### ISSUE TITLE
세팅 관련 질문드립니다.

### ISSUE THREAD

**Issue by OGAYONG** [JonghyeokPark/SWE3003#20]
노트북을 바꿔서 작업하게 되어 다시 설치하였는데
python35설치에서 오류가 발생하는데 어떻게해야하나요?
![default](https://user-images.githubusercontent.com/32060762/38908758-bd2a3d98-42fc-11e8-97c9-ed0896cbe132.png)

**Comment by JonghyeokPark** [comment]
과제 설명서에 나와있는 .repo 파일 제대로 수정하셨는지 확인바랍니다.
해당 문제는 rh-python35가 제대로 설치되지 않아서 발생한 문제입니다.

**Comment by OGAYONG** [comment]
repo 에서 enabled 값을 수정하였습니다만 python35가 설치되지 않습니다.
terminal에서 enabled값을 수정한 후 변경 값을 따로 저장하는 절차가 있나요?

**Comment by JonghyeokPark** [comment]
repo 파일을 제대로 저장했으면 설정은 적용된 것입니다. 
해당 문제는 저도 겪어보지 않아서  정확한 답을 드리기 어렵네요.
혹시 yum udpate를 하면 해결 될 수 있을 것 같습니다.
터미널에 sudo yum update 입력해주세요.

+ 새로운 노트북에 VM을 다시 설치하고 처음부터 진행한 것이 맞나요?  (이미 git, scl-utils, 그리고 SWE3003 repository가 이미 있단느 경고가 의심스럽네요.)

**Comment by OGAYONG** [comment]
repo에서 enabled값을 수정 하였는데 저장을 어떻게 하는지 모르겠습니다.

--그리고 이미 있다는 경고는 python35가 안되길래 제가  git, scl-utils 설치하고 혹시나 해서 한 번 더 입력해서 그런 것 같습니다. 재 설치도 했구요.

**Comment by JonghyeokPark** [comment]
과제 제안서와 동일하게 sudo vim /etc/yum.repos.d/public-yum-o17.repo 
으로 열었다면, enabled=1 로 바꾸시고

키보드의 ESC key를 누르시고, :wq 하시면 됩니다. (콜론 입력후 wq)
다시 열었을 때, 수정한 enabled=1로 되어있으면 저장이 완료된 것입니다.
