### ISSUE TITLE
세팅 관련 질문입니다

### ISSUE THREAD

**Issue by chestnut73** [JonghyeokPark/SWE3003#22]
pip install –upgrade pip 하면 오류 나는데 이거 어떻게 해결해야 하나요..

![11](https://user-images.githubusercontent.com/38512974/38964672-07bfcd44-43b3-11e8-88f5-a60e640a971d.png)

**Comment by JonghyeokPark** [comment]
에러 메세지를 보시면, Permission Denied 가 있습니다. 이는 권한 문제입니다.
pip install --upgrade pip 할때, sudo 를 입력해야 합니다. 
하지만, 과제 안내서를 보면 venv (myvenv) 가상화 환경을 활성화 한 뒤, pip 및 Django를 설치하도록 되어 있습니다. 
현재 상태에서 설치하면, python2.x 버전으로 설치되어 과제를 진행하시는데 문제가 있을 것입니다.
과제안내서를 참고해주세요.
