### ISSUE TITLE
[과제 문의] homework 3 에서 user 수에 관해 질문 있습니다.

### ISSUE THREAD

**Issue by k-young-passionate** [JonghyeokPark/SWE3003#26]
Performance Value 를 입력할 때에 1 user, 4 users 등의 user 인원에 대한 조건이 있는데

이를 1 user 당 1 process 로 해석해서 진행하면 되는 것인지 궁금합니다.

항상 수고하십니다~

**Comment by JonghyeokPark** [comment]
1user 당 1 process로 생각하시면 됩니다.
