### ISSUE TITLE
[과제 문의]  homework3, oracle vm 에서 fio 실행 중 용량문제 관련하여 문의드립니다.

### ISSUE THREAD

**Issue by k-young-passionate** [JonghyeokPark/SWE3003#27]
fio 실행시 oracle vm 에서 용량이 계속 늘어나고

numjobs=32 실행 시 용량 부족이 뜹니다. (size 1G 로 설정)

이전 시행에 따른 데이터를 지우는 방법이 있나요?

감사합니다.

**Comment by JonghyeokPark** [comment]
Oracle VM 디바이스 용량을 여유있게 설정하셨나요?
directory 옵션을 지정하셨으면, 해당 경로에 fio 실험에 쓰이는 파일이 있습니다.
해당 파일을 지워주세요.
