### ISSUE TITLE
[셋팅 문제] VMware와 ubuntu 설치 오류

### ISSUE THREAD

**Issue by dudtjr1067** [JonghyeokPark/SWE3003#28]
Vmware 와 ubuntu 설치를 조교님께서 알려주신대로 순서대로 설치 과정을 했는데 VMware 실행 후 ubuntu를 설치하는데 몇 시간을 기달려도 설치가 안되서 문의드립니다.

**Comment by JonghyeokPark** [comment]
정확한 상황을 몰라서 답변드리기 어렵습니다.
+혹시, 32 bit, 64 bit에 맞게 까셨는지 확인하셨나요?
+컴퓨터 용량 확인하셨나요?
