### ISSUE TITLE
[과제 문의] 결과 Table에 대한 의문점이 있습니다. 

### ISSUE THREAD

**Issue by ray5273** [JonghyeokPark/SWE3003#29]
![default](https://user-images.githubusercontent.com/8529112/39537078-758e8a70-4e73-11e8-96b2-d782bf378400.PNG)
위에 결과 table 에 있는 7번째 column에 정확히 어떤걸 써야 할지 모르겠어서 질문 드립니다.
나머지 6개는 그냥 결과를 read / write 혹은 fsync 1 일때 혹은 fsync 64 일때 
비교를 하여 둘다 적으라는 것 같은데 7번째 column은 앞에 있는 4번째 column을 사용 하라는데 
4번째 column과 7번째 column을 어떤점에서 차이가 있는지 잘 모르겠습니다. 
7번째 column은 2가지 값을 적는게 아니라 그 두 값을 나누라는 뜻인지 궁금하여 질문 드립니다.

**Comment by JonghyeokPark** [comment]
7번항목은 이미 구한 4번항목을 이용하여 Random read , write 의 성능을 비교하는 것입니다.
4번 항목에서는 32user에서 Random Read, Random Write 값을 각각 구하는 것이고,
7번 항목에서는 그 두값을 나누어 비교하는 것입니다.
