### ISSUE TITLE
[과제문의]과제3 oracle vm 질문드립니다.

### ISSUE THREAD

**Issue by wlaud1001** [JonghyeokPark/SWE3003#30]
oracle vm으로 과제를 할 시 용량을 충분히 늘리라고 하셨는데 어떻게 늘릴 수 있는지 질문드립니다.
users의 수를 바꾸기 위해서는 numjobs= 을 수정하면 되는 건가요??
감사합니다!!

**Comment by JonghyeokPark** [comment]
용량을 늘리기 위한 방법은 다음과 같습니다.
1. 현재 가상화 머신 디바이스 파일인 vmdk파일을 vdi로 변경함.
2. vdi 파일에 대해 resize 명령어로 용량 변경
3. vdi 파일을 다시 vmdk 로 변경
4. virtualBox 옵션에서 변경한 vdmk파일을 저장소로 지정
5. oracle vm 접속 후, 파티션 재지정

참고자로 : 
http://technote.kr/156
http://www.dibisis.net/2017/06/19/virtualbox_vmdk_resize/

제가 수행해본 결과, 4 번 이후 Oracle VM이 정상작동하지 않는 것으로 확인되었습니다.
제일 쉬운 방법은 재설치 후, **설치과정에서 변경**해보시기 바랍니다.

**Comment by wlaud1001** [comment]
답변감사합니다!
혹시 지금 가상머신 실제 용량이 20GB정도로 잡혀있는데 더 늘릴 필요가 있나요?
용량이 부족하면 어떤 문제가 생기는지 궁금해서 질문드립니다!

**Comment by JonghyeokPark** [comment]
No space left on device  에러가 발생하고, 수행이 결과가 제대로 나오지 않을 것입니다.
넉넉하게 40GB 이상으로 잡아주세요.
