### ISSUE TITLE
[과제문의] 메모리 용량 오류

### ISSUE THREAD

**Issue by jwkim1104** [JonghyeokPark/SWE3003#31]
<img width="713" alt="error_no space left on device" src="https://user-images.githubusercontent.com/37295681/39564872-db58486e-4ef0-11e8-8376-8f82280832b3.PNG">

주신 표에서 num jobs와 fsync 등의 변수들만 값을 바꾸고 나머지 변수에 대해서는 조교님께서 올려주신 예제문과 같은 형식을 유지했습니다.

-size=1G
--direct=1
--directory=./
--group_reporting
--bs=8KB
--runtime=60

그랬더니 No space left on device라는 오류가 발생해서

어떻게 해결해야하는지 모르겠습니다.

**Comment by JonghyeokPark** [comment]
No space left on device 이는 현대 VM의 디바이스의 용량이 부족하다는 것입니다.
vm 디바이스 용량을 늘려주세요.
