### ISSUE TITLE
[과제 문의] 결과값이 기존 제품이 설명하는 값과 차이가 좀 납니다.

### ISSUE THREAD

**Issue by k-young-passionate** [JonghyeokPark/SWE3003#32]
제가 사용하는 디스크가 최대 속도 Bandwidth 550 / 220 (MB/s), Random IO 98000 / 90000 (IOPS)
로 표기되어 있는데

VM 에서 돌려본 값이 8522 / 8554 (KB/s), Random IO 1076 / 1070 (IOPS) 로 표기된 값과 현저하게 차이가 납니다.

Option 은 size = 512MB, blocksize = 4KB, runtime = 60, fsync = 1 로 두었습니다.

이것이 혹시 VM 의 영향인지, 아니면 다른 원인이 있거나 제가 과제를 잘못 수행한건지 궁금합니다.

감사합니다.

**Comment by JonghyeokPark** [comment]
가상머신에서 성능측정을 하는 것은 실제 디바이스 스펙상의 성능 차이가 나는 것은 당연합니다.
또한 스펙상에서는 fsync 주기나 queue depth 등의 기타 옵션을 따로 명시한대로 동일하게 수행하지 않는 이상 차이가 날 수 밖에 없습니다.
fsync=1이라는 것은 write 1회 수행하고 fsync 를 수행하는 것이기 때문에 성능이 현저히 낮습니다. (디바이스 스펙 결과는 이런 상황에서 하지 않았을 것입니다. 보통, fsync 주기를 좀 높게 잡습니다.

+ 본 과제의 목적은 Sequential I/O와  Random I/O의 성능 차이에 대해 알아보는 것입니다.
