### ISSUE TITLE
[과제 문의] 제출해야하는 3번째 자료에 대해 질문있습니다.

### ISSUE THREAD

**Issue by k-young-passionate** [JonghyeokPark/SWE3003#33]
![image](https://user-images.githubusercontent.com/11757075/39659778-51a1cda8-506b-11e8-92a7-baabcc52dbc4.png)

Compare read & write (sequential vs write) 에서

bandwidth 와 iops 를 비교하라는 것은 값을 비교하란 뜻인가요?

**Comment by JonghyeokPark** [comment]
수행 결과에 대한, Sequential I/O 와 Random I/O 의 차이에 대해 비교해보고 결론을 내리라는 의미 였습니다. 
또한, 표를 채워보시면,  IOPS 로 Bandwidth를 구할 수 있습니다.  Bandwidth를 이용해 구해보셔도 됩니다.
