### ISSUE TITLE
[셋팅 문제] hdparm -I에서 bad/missing sense data가 뜹니다.

### ISSUE THREAD

**Issue by skkuai** [JonghyeokPark/SWE3003#34]
![default](https://user-images.githubusercontent.com/39051279/39697594-5fe8cdb8-522c-11e8-9a19-47bb2b3e2770.JPG)

VMware Ubuntu 상입니다.

어떻게 해결해야할까요? ㅠ.ㅠ

**Comment by JonghyeokPark** [comment]
VMware 등의 가상머신 상에서는 hdparm 명령어가 제대로 동작하지 않습니다.
과제 안내서 11 페이지를 참고해주세요
