### ISSUE TITLE
남은 용량이 모자라서 32 process를 돌리지 못합니다

### ISSUE THREAD

**Issue by ghost** [JonghyeokPark/SWE3003#36]
가상머신 설치하고 나니 남은 용량이 10GB 정도인데
4 process까지는 돌릴 수 있어도
32 process는 무리입니다
혹시 process수를 줄이거나 파일 한개의 size를 줄여도 되는지요?
조교님이 주신 예제코드에는 1GB로 되어있는 사이즈를 100MB로 낮추어도 상관없나요?

**Comment by JonghyeokPark** [comment]
네 가능합니다. 
process는 적어도 8까지는 해주시고, 파일크기도 줄여보세요.
대신, Sequential I/O와 Random I/O 성능차이가 발생해야 합니다. 
(어떻게 수정했는지  보고서에 명시해주세요.)
