### ISSUE TITLE
[과제 문의] 용량 문제 관련

### ISSUE THREAD

**Issue by whitedelay** [JonghyeokPark/SWE3003#37]
앞 질문에서 파일 크기와 numjob수 줄여서 써도된다고 하셨는데 그러면 가상머신 용량 늘릴 필요없이 파일 크기만 줄여서 보고서 제출해도 되나요??

**Comment by JonghyeokPark** [comment]
가상 머신 용량을 늘릴 수 없을 때 조정해서 하시기 바랍니다.
numjobs 줄여도 최소 8개는 유지해주시기 바랍니다.
중요한 점은 sequential I/O 와 random I/O의 성능 차이가 있어야 합니다.
