### ISSUE TITLE
[과제 문의] 결과 테이블 6번 항목에 대해 질문있습니다.

### ISSUE THREAD

**Issue by CAROUL** [JonghyeokPark/SWE3003#38]
![image](https://user-images.githubusercontent.com/39125733/39815636-9cb1984e-53d3-11e8-9dc2-ba5b0cb4d96a.png)

6번 항목은 단순히 두 값을 비교하라는 뜻인가요? 아니면 7번 항목처럼 나누는 것인가요?

+)

![image](https://user-images.githubusercontent.com/39125733/39815948-ab083bf4-53d4-11e8-9a63-b953a0c2dcda.png)

random read의 결과값에 보면 IOPS (4373)와 bandwidth(35.8MB/s)가 둘 다 나와있는걸 볼 수 있습니다.
그런데 표에 나온대로 IOPS * 4KB 를 하면 17.49MB/s 가 나오는데, 왜 계산값과  FIO 결과값이 다른지 궁금합니다.

**Comment by JonghyeokPark** [comment]
6번 항목은 Random Read IOPS 값을 활용하여 Bandwidth 값을 각각 구하고, 나누어 비교해 보면 됩니다.
+ 혹시, Random Read 하실때 fio 옵션 중 block size 값을 4KB 로 하셨나요?
