### ISSUE TITLE
FIO result screen shot관련

### ISSUE THREAD

**Issue by mlee528** [JonghyeokPark/SWE3003#39]
screen shot을 각 명령에 대하여 모두 찍어서 보내드려야하나요...?
아니면 맨 처음에 randwrite로 command 올려주신거 그 예시대로 그 부분만 스크린샷 찍어서 보내드리면되는건지요

**Comment by JonghyeokPark** [comment]
fio 명령어를 확인해보려고 스크린샷을 요청 드렸습니다.
fio 명령어만 잘 보이면 됩니다.
