### ISSUE TITLE
[과제 내용] 과제 내용 관련 질문입니다

### ISSUE THREAD

**Issue by jiwoogit** [JonghyeokPark/SWE3003#4]
기차가 여러 역을 경유할 때 기차의 남은 좌석과 같은 사항들도 모두 고려하여 데이터베이스를 만들어야 하나요?

**Comment by JonghyeokPark** [comment]
코레일 기차 예약 시스템을 설계하는데 제한 사항은 없습니다. 다만, 기차 예약 시스템에 필요한 기능들을 생각해보시고 그 기능들을 위한 데이터베이스를 설계하시면 됩니다.
