### ISSUE TITLE
[과제문의] vmware 용량 40이상설정 후 용량부족문제

### ISSUE THREAD

**Issue by wlaud1001** [JonghyeokPark/SWE3003#40]
![default](https://user-images.githubusercontent.com/28920463/39850181-e7ce7834-544a-11e8-99e5-aecddee30a2d.png)

![default](https://user-images.githubusercontent.com/28920463/39850185-ec5fc02e-544a-11e8-84e5-378e0a075c97.png)

vmware의 용량을 40이상으로 잡았는데도 용량부족 문제가 발생하여 혹시 코드에 문제가 있나 싶어서 질문드립니다. 아니라면 어떻게 해결하는 것이 좋을까요?
감사합니다.

**Comment by JonghyeokPark** [comment]
코드에는 문제 없습니다. 
다만, 현재 동시에 수행되는 프로세스 수가 32여서 용량 부족문제가 발생한 것 같습니다.
numjobs 옵션을 8로 줄여서 해보세요. 
또한, --time_based 옵션을 주고 최소 15분 이상은 돌려야 sequential I/O random I/O 차이가 발생합니다.
