### ISSUE TITLE
[과제문의] io값

### ISSUE THREAD

**Issue by wlaud1001** [JonghyeokPark/SWE3003#41]
![wa](https://user-images.githubusercontent.com/28920463/39876100-51df0a7e-54ad-11e8-9893-e937f6ffa798.png)

코드를 돌렸는데 어떤 것을 비교해야 되는지 잘 모르겠어서 질문드립니다. 위의 것들 중 어느것을 비교해야 하나요??
감사합니다.

**Comment by JonghyeokPark** [comment]
표 항목을 보시면, IOPS, bw 값을 채워넣으시면 될 것 같습니다.
나머지 항목들은 fio 수행 결과에 대한 자세한 세부내용들입니다. (지연시간, 수행시간 등)

**Comment by wlaud1001** [comment]
가운데 박스에 bw의 avg는 2431.54인 반면에 맨 아래 박스의 bw는 18.0로 kib를 mib로 환산해도 값의 차이가 좀 나는데 무엇을 써야하는 것인지 궁금해서 질문드립니다. 감사합니다.

**Comment by JonghyeokPark** [comment]
가운데 박스의 bw avg 값은 각 프로세스 당 편균 bandwidth 값을 의미합니다.
보통, fio 결과에서의 bandwidth 값은 맨 위의 값을 활용합니다.

**Comment by wlaud1001** [comment]
감사합니다!

**Comment by HaeunKim1** [comment]
이 이슈를 보기 전에 bw avg 값으로 보고서를 다 써버렸는데

이대로 해도 큰 상관은 없나요?
