### ISSUE TITLE
[과제 문의] 6번, 7번 항목 값 구할 때 user 수에 대해

### ISSUE THREAD

**Issue by skkuai** [JonghyeokPark/SWE3003#42]
1user인 경우만 구하면 되나요?

**Comment by JonghyeokPark** [comment]
7번항목을 보면, 4번항목을 이용합니다.
4번 항목은 32user로 수행합니다. 다만, 가상머신의 용량이 부족한 경우, 32user에서 8user로 줄이셔도 됩니다.
