### ISSUE TITLE
[과제 문의] 제품 스펙에 Random I/O 정보가 없습니다.

### ISSUE THREAD

**Issue by skkuai** [JonghyeokPark/SWE3003#43]
공식 회사 홈페이지에서 아무리 찾아도 Data Trasfer Rate 만 보입니다만, 
다른 benchmark 사이트를 참조해야할까요?

참고로 제 HDD model 이 WD 사의 WD 20EZRZ 이고(2TB), 공식 제품 명세서를 찾아본 결과입니다..

https://www.wdc.com/products/internal-storage/wd-blue-pc-desktop-hard-drive.html

![default](https://user-images.githubusercontent.com/39051279/39877871-fbf00ab4-54b1-11e8-9c15-8207604bf9d4.JPG)

![2](https://user-images.githubusercontent.com/39051279/39878023-508f59bc-54b2-11e8-94c8-194aca7cb726.JPG)

아니면 제가 뭔가 크게 잘못 알고 있거나 잘못 조사한 걸까요?

**Comment by JonghyeokPark** [comment]
네 다른 벤치마크 사이트를 통해 조사해주세요.
Userbenchmark 사이트 참조해주세요. (http://hdd.userbenchmark.com/WD-Blue-2TB-2015/Rating/3521)
