### ISSUE TITLE
[과제문의] fsync 옵션을 없애도 random write값이 더 높습니다.

### ISSUE THREAD

**Issue by junghr77** [JonghyeokPark/SWE3003#44]
공지하신 대로 fsync 옵션을 
없앴더니 둘 사이의 차이는 많이 줄었지만 여전히 random write가 sequential write보다 높습니다.
어떻게 하면 좋을까요?
![randwrite](https://user-images.githubusercontent.com/27476271/39915300-8997a24c-5542-11e8-9197-8e5ee03b813e.jpg)
![seqentialwrite](https://user-images.githubusercontent.com/27476271/39915304-8d582122-5542-11e8-9737-b4f6db9e8870.jpg)

**Comment by JonghyeokPark** [comment]
혹시 시간과 파일 크기를 늘려서 해보셨나요? 
적어도 10G 파일에 대해서 비교해야 차이가 발생하는 것을 확인했습니다.
계속 하다가, 안되시면 보고서에 명시해주세요.
