### ISSUE TITLE
[과제문의] 리포트 마지막 비교

### ISSUE THREAD

**Issue by wlaud1001** [JonghyeokPark/SWE3003#46]
리포트 마지막에 seq의 bw와 rand의 iops를 비교하라고 명시되어있는데
말 그대로 seq의 bw와 rand의 iops를 비교하면 되는것인가요? 아니면 seq와 rand 의 bw와 iops를 각각 비교하라는 뜻인가요?

또한 read일때와 write일때를 나누어 비교하라고 되어있는데 read일 때와 write일 때의 차이가 발생하는건가요??

감사합니다.

**Comment by JonghyeokPark** [comment]
결과를 작성한 표를 바탕으로 전체적인 결론을 내는  문제 입니다.
Sequential I/O 와 Random I/O 의 차이를 수치상으로 몇배 차이 나는지 확인하고 이유를 수업 때 배운 내용과 연관지어 설명하면 좋을 것 같습니다.
