### ISSUE TITLE
[과제 문의] VM 관련

### ISSUE THREAD

**Issue by woolimcho** [JonghyeokPark/SWE3003#47]
안녕하세요. 과제 관련 질문이 있습니다.
1. 꼭 Vmware나 Virtualbox같은 VM상에서 테스트를 수행해야 하나요? 저 같은 경우에는 데스크탑에 이미 우분투가 설치되어 있습니다.

2. 보통 VM 설정이 직접 저장장치에 접근하는게 아니라 .vmdk 같은 가상 디스크 파일을 만들어서 사용하도록 되어 있어 제조사에서 제공하는 specification보다 훨씬 낮은 성능으로 결과가 나올 것 같습니다. 이런 경우 어떻게 해야 하나요?

**Comment by JonghyeokPark** [comment]
1. 리눅스에서 바로 하셔도 됩니다.
2. 스펙이랑은 당연히 차이가 납니다. sequential I/O Randomn I/O 성능 차이 확인하시면 됩니다.
