### ISSUE TITLE
[과제 문의] 측정 결과가 너무 크게 나옵니다

### ISSUE THREAD

**Issue by guswh11** [JonghyeokPark/SWE3003#48]
![kakaotalk_20180511_221104076](https://user-images.githubusercontent.com/38255974/39965385-9dfeaa8c-56d2-11e8-843a-d815d96e3025.png)
vm은 외장 하드에 있고 직접 대역폭 측정 결과 sequential/random read의 성능이 38MB/s 정도밖에 되지 않는데도 fio로 측정하면 저런식으로 대역폭 값이 1000MB/s가 넘게 나옵니다 
write 값은 정상적으로 나오는 것 같은데 명령어에 문제가 있는건가요?

**Comment by guswh11** [comment]
위에 스크린샷은 어제의 결과이고 오늘 같은 코드로 다시 돌려봤더니 정상 범주로 나옵니다 ㅠㅠ무슨 차이인가요?

**Comment by JonghyeokPark** [comment]
파일 사이즈가 1G 여서 상당부분이 메모리에 캐싱되어 있어서 그럴 수 있습니다. 자세한 환경은 직접 상황을 봐야 알 것 같습니다.
