### ISSUE TITLE
[과제문의] Rand. RD/WR IOPS(32 users)와 Random WR IOPS / Random RD IOPS(using column#4)의 차이점

### ISSUE THREAD

**Issue by chahk0129** [JonghyeokPark/SWE3003#49]
처음거는 randrw로 측정한 IOPS이고 마지막꺼는 randwrite, randread를 따로 해서 각 IOPS를 작성하라는 건가요? 저는 처음 측정할 때부터 sequential이든 random이든 read하고 write하고 동시에 하면 측정값이 뭉개질 수 있다고 보고 따로진행했었는데 처음부터 다시 해야되는건가요?

**Comment by JonghyeokPark** [comment]
표 1번 항목은 Sequential Read 와 Write의 bandwidth 를 측정하는 것입니다.
마지막 항목은 Random Write IOPS를 측정하고, 4번 항목을 활용하여 Random Read IOPS 를 구한 뒤 비교하는 것입니다.
모든 항목에 대해 FIO 의 rw 혹은 randrw (read write 동시에 수행하는 옵션)은 사용하지 않습니다. 각각 따로 측정하는 것이 맞습니다.
