### ISSUE TITLE
[ 실험 환경 셋팅 ] 셋팅이 안돼요

### ISSUE THREAD

**Issue by guswh11** [JonghyeokPark/SWE3003#5]
앞에 단계까지 문제없이 했는데 다음과 같은 오류가 뜨면서 서버가 뜨지 않습니다. 
![kakaotalk_20180411_002600626](https://user-images.githubusercontent.com/38255974/38566623-a2e4428c-3cd3-11e8-8bb0-f5f8f1276dc5.png)

**Comment by JonghyeokPark** [comment]
scott 계정으로 접속하려는데 실패한 것 같습니다.
원인은 아마, scott 계정을 실습하시면서 지우신 것 같습니다.
오라클 데이터베이스를 아래와 같이 초기화 해주세요.
(Oracle Virtual Box VM 설치 pdf 참조)

터미널창 열어서
sqlplus system/oracle
@ /u01/app/oracle/product/12.2/db_1/rdbms/admin/utlsampl.sql
sqlplus scott/tiger 계정 접속 잘되는지 확인.
