### ISSUE TITLE
[과제 문의] Sequential Write 가 Sequential Read 보다 빠르게 나옵니다

### ISSUE THREAD

**Issue by eunchan-park** [JonghyeokPark/SWE3003#50]
제품 specification 에는 분명 Read 보다 Write가 훨씬 느림에도 불구하고 Sequential Write 가 Read보다 빠르게 나옵니다. Runtime 을 늘려도 마찬가지 입니다.  Size를 2G로 늘려보았지만 거의 비슷하게 나옵니다. 무슨 문제가 있는것인가요?  
![seqread](https://user-images.githubusercontent.com/31975515/39979619-9fc83620-5782-11e8-9b3c-3d3cb348172e.JPG)

![seqreadresult](https://user-images.githubusercontent.com/31975515/39979724-2d48422e-5783-11e8-9794-aa156e5a9989.JPG)

![seqwrite](https://user-images.githubusercontent.com/31975515/39979621-a4a71030-5782-11e8-8928-30cae61cfcb0.JPG)

![seqwriteresultjpg](https://user-images.githubusercontent.com/31975515/39979727-2e9d290a-5783-11e8-8327-bf104ab30838.JPG)

**Comment by pec9399** [comment]
size 를 2G로 늘려봤으나 여전히 똑같습니다.

**Comment by JonghyeokPark** [comment]
write 실험하실 때 fsync = N 옵션을 주시고 수행해보세요. (N이 작을수록 write 성능은 안좋게 나옵니다.)
