### ISSUE TITLE
Problem Criteria 관련하여 질문있습니다.

### ISSUE THREAD

**Issue by k-young-passionate** [JonghyeokPark/SWE3003#6]
5. Handling duplicates in your table

여기에서 duplicates 를 dummy data 에서 발생시킨 후 둘 중 원하는 데이터 하나를 제거하라는 뜻인지

아니면 Insertion 을 할 때 PK 의 경우 자동으로 생성되게 하여 Duplicates 가 발생할 수 있다는 전제 하에 데이터 중복을 막는 방법을 강구하라는 것인지 궁금합니다.

감사합니다.

**Comment by JonghyeokPark** [comment]
5번의 경우에는 Dummy data로 중복이 있는 데이터를 집어넣고, 조회를 할때  출력된 데이터에 중복이 없도록 하라는 것입니다. 즉, 전자의 경우가 맞습니다.
