### ISSUE TITLE
[제출 관련] 제출관련해서 질문 드립니다.

### ISSUE THREAD

**Issue by ray5273** [JonghyeokPark/SWE3003#7]
제출은 조원 중 아무나 한명이 아이캠퍼스에 올리면 되는건가요?
아니면 올려주신 엑셀파일의 조별로 제일 위에 적혀있는 사람이 올리는건가요?
![default](https://user-images.githubusercontent.com/8529112/38630634-79db1206-3df2-11e8-9c28-a491ac4310ff.PNG)

**Comment by JonghyeokPark** [comment]
팀원 중 한명만 업로드하시면 됩니다. 
보고서에 팀원 명시해주시면 됩니다.
