### ISSUE TITLE
[실험 환경 셋팅] can not find valid baseurl for repo: ol7_latest

### ISSUE THREAD

**Issue by wlaud1001** [JonghyeokPark/SWE3003#8]
can not find valid baseurl for repo: ol7_latest 라는 문구가 계속 뜹니다.

**Comment by JonghyeokPark** [comment]
어느 상황에서 발생한 것인지 알려주세요 (스크린샷 첨부)
과제 설명서 5페이지대로 수정은 하셨나요?
