### ISSUE TITLE
Problem Criteria 관련 질문입니다. 

### ISSUE THREAD

**Issue by kyungmax** [JonghyeokPark/SWE3003#9]
2번 항목의 sort with group by function의 의미가 잘 와닿지 않습니다. 

group by 한 결과를 가지고 order by하는 sql문을 작성하는것이 맞나요? 

감사합니다.

**Comment by JonghyeokPark** [comment]
2번 문제의 의도는 "GROUP BY" 와 "ORDER BY" 를 활용하는 것입니다.
두 함수를 활용하기만 하면 됩니다.
